<?php

/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array
 */
function shano_shopping_cart_theme($existing, $type, $theme, $path) {
  return [
    'shopping_cart_index' => [
      'variables' => ['events' => NULL, 'total' => NULL]
    ],
  ];
}

function shano_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'shano/shano-main';
}

function shano_shopping_cart_page_attachments(array &$attachments) {
  $user_is_admin = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id())->hasRole('administrator');
  if (user_is_admin) {
    $attachments ['#attached']['library'][] = 'shano_shopping_cart/toolbar-stripe-keys-icon';
  }
}
