<?php

/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array
 */
function shano_shopping_cart_theme($existing, $type, $theme, $path) {
  return [
    'shopping_cart_index' => [
      'variables' => ['events' => NULL, 'session_id' => NULL, 'stripe_public_key' => NULL]
    ],
  ];
}

function shano_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'shano/shano-main';
}
